### ISSUE TITLE
New Feature KeyHandler

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/GameMecha#46] opened 2018-05-23 10:19 UTC
Morphs have a on: send: to

Similiar to that I want to register functions to my KeyHandler which are called when a specific button is down/up.

Example:
self registerToKeyHandlerOn:  Character arrowUp state: #down send: #jump to: self

**Comment by ben243871694** [comment] 2018-05-27 15:55
closed, duplicate of already existing userstory. explanation copied.

**Closed by ben243871694** 2018-05-27 15:55 UTC
